### ISSUE TITLE
Broken graphic Nvidia gpu

### ISSUE THREAD

**Issue by Sangkwun** [tobspr/RenderPipeline#111]
![image](https://user-images.githubusercontent.com/23003207/57073505-352a7e80-6d1c-11e9-82e6-e54b3a037f2b.png)

NVIDIA-SMI 418.40.04    Driver Version: 418.40.04    CUDA Version: 10.1
I'm running on RTX2080ti is it can be a problem?

**Comment by tobspr** [comment]
I have not tested the render pipeline on the new RTX yet, it might be very well that its bugged there :/

**Comment by paperManu** [comment]
Hi,
I have the same issue on a GTX 2070 even without any plugin activated. And the issue seems to be present too on a GTX 1060 with the 430 drivers.
As far as I can tell, it looks like a problem with the depth buffer. Do you have any hint regarding what could be the cause? I am willing to help solve it.

**Comment by bluekyu** [comment]
I also have the same issue on RTX2080Ti and 425 drivers.

It can be solved by disabling the below optimization:
https://github.com/tobspr/RenderPipeline/blob/8e0212d88a138de59f08fe9d6dce148227cf8216/rpcore/shader/render_pipeline_base.inc.glsl#L33-L35

However, SMAA plugin has another issue:
![screenshot](https://user-images.githubusercontent.com/937305/57372201-f7bc6a00-71cf-11e9-949f-dcfdd91703c0.png)
This happens a little bit later and the black area grows bigger.
It is caused by "resolve_smaa" shader.

**Comment by paperManu** [comment]
Indeed the fix works for me. Thanks a lot bluekyu.

**Comment by Sangkwun** [comment]
@bluekyu Thanks for your help. As you said the black area has appeared on my screen too but the issue is solved.

**Comment by rdb** [comment]
Not sure why this was closed, but in any case, I have just pushed the fix for this to the master branch.
