### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by Khailz** [tobspr/RenderPipeline#22]
Would a simple 2to3 make this compatible enough for python 3?

**Comment by pennomi** [comment]
I've actually made this work before and 2to3 isn't quite enough sadly. There are a few Unicode and integer division updates that need manually applied after the script is run. Pretty routine for anyone familiar with porting libraries.

With a couple of `__future__` imports, and possibly with a small shim layer the code should work on both 2 and 3 without having to change it at all.

**Comment by Khailz** [comment]
I'm not too keen on porting, so I'll probably wait until he is done with the refactor.

**Comment by tobspr** [comment]
@pennomi can you maybe explain which particular issues you had while porting? That way I could already include fixes to them in the refactored version.

**Comment by pennomi** [comment]
(Warning! This post ended up being longer than I expected...)

It was some time ago that I did the porting, but the most common cases were `xrange`/`iteritems` (which are taken care of by 2to3), relative imports (also taken care of by 2to3), print function (2to3 ftw), integer division, and one or two small unicode/bytes errors. There were a couple of other little things taken care of by 2to3, but they were all backwards-compatible with Python 2. (Like exception handling using the `as` syntax.)

## individual issue breakdown

#### xrange/iteritems

The `xrange` and `iteritems` problems could be fixed by either using the non-generator equivalents (ie. `range`) on Python 2 (which could impact memory usage, but maybe try it?) or having a shim file that defines them properly: `xrange = range` if no `xrange` is found. The library [`six`](https://pythonhosted.org/six/) does this for you, and you can, for example, just import `xrange` from `six` instead of using the builtin.

#### relative imports

Relative imports should be prefixed with a `.` in Python 3. You can force this behavior in Python 2 by using `from __future__ import absolute_import`. Your imports would change like this:

    -from DebugObject import DebugObject
    +from .DebugObject import DebugObject

The logic behind this change was to make relative imports explicit and to avoid namespace collisions if you *also* had a DebugObject module in your top level folder.

Technically you don't *have* to do the future import; the syntax is supported in Python 2. What the future import does is drop the old Py2-specific behavior.

#### print function

The print function is the most obvious case, and 2to3 handles it fine. You can enable the behavior in Py2 by importing `from __future__ import print_function`

#### integer division

The integer division problem can be shown on your current files by putting the line `from __future__ import division`. This is because in Py3, `1 / 2 => .5` but in Py2 `1 / 2 => 0`. To do explicit integer division in Python 3 (or in Python 2 if you've imported future functionality) use the floordiv operator which gives what you want. (`1 // 2 => 0`)

This was the bulk of my manual changes to get the library to work on Python 3. 2to3 can't detect these cases automatically. I basically fixed these case-by-case until the system stopped crashing. The issues generally appear as an `IndexError` I believe.

#### unicode

The unicode problem is probably the trickiest, because it is the largest inconsistency between the Python 2 and Python 3 APIs. First thing, you'll want to do `from __future__ import unicode_literals`. I also had to apply the following patch, which may or may not work on Python 2:

    @@ -111,8 +111,9 @@ class IESLoader(DebugObject):
             # Open the IES file
    -        with open(filename, 'rt') as handle:
    +        with open(filename, 'rb') as handle:
                 content = handle.read()
    +            content = content.decode('ISO-8859-1')

## summary

Summed up, *most* things can be fixed by first running 2to3, then putting the following line at the top of every file:

    from __future__ import absolute_import, unicode_literals, division, print_function

then fixing the resulting errors. For everything else, there's `six`. It really shouldn't take much longer than a few hours to do the port, and once you're done, you just keep following the good patterns established and your codebase should run on both Python 2 and 3 with no changes.

I've ported more than a dozen projects/libraries, so I'm very familiar with what needs to happen. Feel free to ask if any of the above doesn't make sense. I'm pretty short on time lately, but if you want, I'll happily make some time to assist with this effort. Gotta push Python 3 adoption! :smile: 

(Also, if I ever rewrite my Panda3d pip installer patch and get it merged, it'll make it easy to have multiple Panda3d versions installed to test against.)

**Comment by tobspr** [comment]
Wow, thanks, thats a bunch of information! I will get a python3 build and try to make it compatible on both python2 and python3. I'm not sure if six is actually required, I think I can just use range() for smaller lists, and since there are no big loops in the pipeline, It should be fine. If I have further problems, I will have a look at six tho.
Thanks for the detailed information! :)

**Comment by tobspr** [comment]
**Update**: I just committed a new version supporting both Python 2 and 3, it was easier than I initially thought, I just ran 2to3 and fixed some smaller errors, thanks for your help! :)

**Comment by tobspr** [comment]
Python 2 and 3 support was added to the refactoring_beta branch.
