### ISSUE TITLE
Mesa 3d or proprietary gl library

### ISSUE THREAD

**Issue by alabd14313** [tobspr/RenderPipeline#27]
Hi!
Do you use mesa 3d or nvidia-gl or etc?
Mesa implemented openGL 4.2. How you implement this pipeline?

Another quick question: Can I use this pipeline with my python 3 compiled panda3d? and can I use this pipeline with c++ (like panda3d c++ api)?

**Comment by tobspr** [comment]
I think panda supports mesa, I'm not sure what feature set mesa supports tho. If mesa supports ARB_image_load_store then the pipeline is most likely to run there, otherwise not.


You should be able to use the refactored pipeline with Python 3, If any problems occur, please let me know so  I can fix those isuses. The old pipeline (the version from the master branch) is not compatible with python 3.

You can also use the pipeline from c++, however, since a big part of the pipeline is python, you would have to store the render pipeline in a PyObject and call methods like add_light on that PyObject.
The lighting system itself is written in C++ tho, so you can store lights as c++ objects in your code.

Cheers,
tobspr

**Comment by rdb** [comment]
You should use the proprietary driver from NVIDIA.  The Mesa drivers are slowly catching up in their OpenGL 4 support, but they're not there yet.  They're getting pretty close, though, so maybe in the near future.

**Comment by alabd14313** [comment]
Thanks for your attention!
I prefer mesa 3d even with it's slow development because of FOSS philosophy and because of I'm a CS student and I don't like proprietary closed source apps!!!
Please see this site:
http://mesamatrix.net/
Panda3d 1.9 works fine in linux and mesa. I will try to test this pipeline and eventually it haven't any problem if have written in panda 3d openGL.

**Comment by rdb** [comment]
As you see on that matrix, compute shaders (ARB_compute_shader) are not
currently supported.  They're working on it, though, so maybe soon!

**Comment by alabd14313** [comment]
Thanks!
