### ISSUE TITLE
Many issues on GeForce 1070

### ISSUE THREAD

**Issue by rdb** [tobspr/RenderPipeline#61]
I recently got a GeForce 1070, unfortunately the pipeline runs very poorly (12 fps at best) and shows bad artifacts, both on Windows and Linux:
http://rdb.name/2016-07-19-224127_1920x1080_scrot.png

The shadows randomise every frame, the camera wobbles, and some parts of objects go missing depending on the camera position.

PSSM splits: http://rdb.name/2016-07-19-224839_1601x896_scrot.png
Buffers: http://rdb.name/2016-07-19-225024_1136x647_scrot.png

Disabling all plug-ins fixes most issues except for the flickering (note the foreground card being chopped off):
http://rdb.name/2016-07-19-225855_1561x834_scrot.png

Any suggestions for where to start debugging would be greatly appreciated.  I can attach an apitrace if it is helpful.

**Comment by tobspr** [comment]
Ah, thanks for bringing this up again :)

Sounds like some driver issue, from what I can see in the buffers it looks like the normals are going wrong - Could you make a screenshot with the "Normal" render mode enabled?

The other buffers look fine so far (Except for AO, but I believe this is caused by the incorrect normals), so I believe something is going wrong in the GBuffer stage.

**Comment by rdb** [comment]
Normal render mode:
http://rdb.name/2016-07-30-125409_1592x896_scrot.png

AO render mode:
http://rdb.name/2016-07-30-125451_1587x895_scrot.png

I found out that the flickering missing part of the cards is caused by the floor plane.  If I lower the floor plane to Z=-10 it goes away.  Might that be a depth buffer precision issue?

**Comment by tobspr** [comment]
Okay seems there are two issues:

1. The depth buffer seems to be random or not present, at least objects are overlapping which should not (Looks like it maybe contains random contents?)

2. The normals are completely wrong on objects without a normal map - Maybe something is going wrong while loading the empty normal map? 

After all, this looks very strange, and I believe its nothing caused by the Render Pipeline / Panda3D itself, but by a weird driver - Did you have the chance to test other driver versions yet?

**Comment by rdb** [comment]
NVIDIA finally released a new Linux driver, which fixed the issues.

The performance is still unexpectedly bad for such a high-end card.  I'll have to investigate that issue later, when I have more time.  It isn't bad when I disable all plug-ins, so it's gotta be one of the plug-ins that's causing it.
