### ISSUE TITLE
compilation error can not found file LinearMath.lib

### ISSUE THREAD

**Issue by sazearte** [tobspr/RenderPipeline#74]
hello, i have this error when i try to compile pipeline:
LINK : fatal error LNK1104: can not open file LinearMath.lib

I'm in Windows 10 x64 with VS2010

**Comment by tobspr** [comment]
Hi, which version of Panda3D do you use? A buildbot one or a self-compiled one?
Also, could you attach the full log please?

Best regards,
Tobias

**Comment by sazearte** [comment]
i try with last panda3d windows version with python 3.5, i try too with old version (december 2016) but i have this problem too.

**Comment by wezu** [comment]
I think it's the same issue as https://github.com/tobspr/RenderPipeline/issues/71

**Comment by sazearte** [comment]
yes but i have not a folder thidparty, because i have not compile panda3d, i only donwload the build version from panda3d website.

**Comment by rdb** [comment]
@tobspr Why do we require the Bullet thirdparty library to compile the pipeline, again?

**Comment by tobspr** [comment]
@rdb Its a "feature" I added which detects if panda was compiled with bullet, and if so, searches for the bullet libraries. However, since it seems to do more harm than good, I guess it would be a good idea to remove it again, and let the user decide which libraries he wants to link to.

However, there is the problem with eigen: iit needs to be on the include path if panda was compiled with eigen. I guess I will just remove bullet and freetype from the list of modules which are automatically linked/included if panda was built with them, and keep eigen in it.

**Comment by rdb** [comment]
@tobspr Panda SDK ships with Eigen headers already from 1.9.1 and up (since it's a header-only lib anyway).

**Comment by tobspr** [comment]
@rdb Ah, cool, didn't know that. I guess I can just remove the logic then

**Comment by tobspr** [comment]
@sazearte I just committed a fix, can you try rerunning the setup script?

**Comment by sazearte** [comment]
your fiw work, thank my problem is solved.
